name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - sympy
  - matplotlib
  - pip
  - pip:
    - openseespy==3.7.1.2
    - opsvis==1.2.23
    # - jupyter-book
    - .